# Generated by Django 5.2.6 on 2025-09-16 11:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodule',
            name='module',
            field=models.CharField(choices=[('CORE', 'Recursos Básicos'), ('TMS', 'Controle de Transporte'), ('PDV', 'Ponto de Venda'), ('ERP', 'Gestão de Recursos Empresariais'), ('WMS', 'Controle de Estoque')], max_length=10),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(default='BR', max_length=2)),
                ('state', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=128)),
                ('district', models.CharField(blank=True, max_length=128, null=True)),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=32, null=True)),
                ('complement', models.CharField(blank=True, max_length=128, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('place_id', models.CharField(blank=True, max_length=128, null=True)),
                ('geohash', models.CharField(blank=True, max_length=16, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'indexes': [models.Index(fields=['country', 'state', 'city'], name='core_addres_country_2475af_idx'), models.Index(fields=['postal_code'], name='core_addres_postal__e6c232_idx')],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_type', models.CharField(choices=[('person', 'Pessoa Física'), ('company', 'Pessoa Jurídica')], default='person', max_length=10)),
                ('full_name', models.CharField(max_length=255)),
                ('fantasy_name', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.CharField(blank=True, max_length=32, null=True)),
                ('state_registration', models.CharField(blank=True, max_length=32, null=True)),
                ('municipal_registration', models.CharField(blank=True, max_length=32, null=True)),
                ('primary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('primary_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('payment_term', models.CharField(choices=[('cash', 'À vista'), ('net15', '15 dias'), ('net30', '30 dias'), ('net45', '45 dias'), ('net60', '60 dias')], default='cash', max_length=10)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_blocked', models.BooleanField(default=False)),
                ('notes_erp', models.TextField(blank=True, null=True)),
                ('loyalty_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('delivery_time_window_start', models.TimeField(blank=True, null=True)),
                ('delivery_time_window_end', models.TimeField(blank=True, null=True)),
                ('requires_scheduling', models.BooleanField(default=False)),
                ('unloading_requirements', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.account')),
                ('preferred_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_customers', to='core.business')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('billing', 'Cobrança (ERP)'), ('shipping', 'Entrega (TMS/ERP)'), ('visit', 'Visita / Correspondência'), ('home', 'Residencial'), ('other', 'Outro')], default='shipping', max_length=16)),
                ('is_primary', models.BooleanField(default=False)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=64, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_addresses', to='core.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_addresses', to='core.customer')),
            ],
            options={
                'verbose_name': 'Customer Address',
                'verbose_name_plural': 'Customer Addresses',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='customers', through='core.CustomerAddress', to='core.address'),
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('email', 'Email'), ('mobile', 'Celular'), ('whatsapp', 'WhatsApp'), ('phone', 'Telefone'), ('other', 'Outro')], default='mobile', max_length=16)),
                ('value', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.customer')),
            ],
            options={
                'verbose_name': 'Customer Contact',
                'verbose_name_plural': 'Customer Contacts',
            },
        ),
        migrations.AddIndex(
            model_name='customeraddress',
            index=models.Index(fields=['customer', 'role', 'is_primary'], name='core_custom_custome_dfd702_idx'),
        ),
        migrations.AddConstraint(
            model_name='customeraddress',
            constraint=models.UniqueConstraint(fields=('customer', 'address', 'role'), name='uniq_customer_address_role'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['Account', 'full_name'], name='core_custom_Account_abde3c_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['Account', 'document'], name='core_custom_Account_a10e97_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active'], name='core_custom_is_acti_4a3f48_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('Account', 'document'), name='uniq_customer_account_document'),
        ),
        migrations.AddIndex(
            model_name='customercontact',
            index=models.Index(fields=['customer', 'type', 'is_primary'], name='core_custom_custome_e0bf0f_idx'),
        ),
    ]
