# Generated by Django 5.2.6 on 2025-09-16 11:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_accountmodule_module_address_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('email', 'Email'), ('mobile', 'Celular'), ('whatsapp', 'WhatsApp'), ('phone', 'Telefone'), ('other', 'Outro')], default='mobile', max_length=16)),
                ('value', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.RemoveIndex(
            model_name='customercontact',
            name='core_custom_custome_e0bf0f_idx',
        ),
        migrations.RemoveField(
            model_name='customercontact',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customercontact',
            name='type',
        ),
        migrations.RemoveField(
            model_name='customercontact',
            name='value',
        ),
        migrations.AddField(
            model_name='customercontact',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_contacts', to='core.customer'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['type', 'value'], name='core_contac_type_fb1563_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('type', 'value'), name='uniq_contact_type_value'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='customers', through='core.CustomerContact', to='core.contact'),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='contact',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='customer_contacts', to='core.contact'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='customercontact',
            index=models.Index(fields=['customer', 'is_primary'], name='core_custom_custome_6c7e9c_idx'),
        ),
        migrations.AddConstraint(
            model_name='customercontact',
            constraint=models.UniqueConstraint(fields=('customer', 'contact'), name='uniq_customer_contact'),
        ),
    ]
