# Generated by Django 5.2.6 on 2025-09-18 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.account'),
            preserve_default=False,
        ),
    ]
